export const ORDER_STATUS = Object.freeze({
  BEFORE_PAYMENT: 1,
  PAYMENT_PROCEEDING: 2,
  PAID: 3,
  PURCHASE_CONFIRMED: 4,
  CANCLE_PAYMENT: 5,
  REFUND_REQUESTED: 6,
  REFUNDED: 7,
  PARTIAL_CANCELLATION: 8,
});

export const SHIPMENT_STATUS = Object.freeze({
  PREPARING_PRODUCT: 1,
  SHIPPINGINPROGRESS: 2,
  SHIPPING_COMPLETED: 3,
  PURCHASE_CONFIRMED: 4,
  ORDER_CANCLED: 5,
  REFUND_REQUESTED: 6,
  REFUND_COMPLETED: 7,
});
